---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
    - main
    - master
  event:
    - pull_request

steps:
  - name: install dependencies php
    image:  php:7.4-cli-alpine
    commands:
      - COPY --from=composer:2.5.1 /usr/bin/composer /usr/bin/composer
      - composer install --no-interaction --no-progress
  - name: install dependencies node
    image: node:16
    commands:
      - npm i
      - npm run build