---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
    - main
    - master
  event:
    - pull_request

steps:
  - name: install dependencies php
    image:  php:7.4
    commands:
      - composer install --no-interaction --no-progress
  - name: install dependencies node
    image: node:16
    commands:
      - npm i
      - npm run build